language: python

python:
    - 3.6

jobs:
  include:
    - os: osx
      osx_image: xcode12
      language: sh
      env:
        - HOMEBREW_NO_INSTALL_CLEANUP=1
        - HOMEBREW_NO_ANALYTICS=1

addons:
    apt:
       packages:
            - build-essential
            - curl
            - git
            - pkg-config
            - gzip
            - software-properties-common
            - python3-dev
            - python3-setuptools
            - python3-pip
            - libgdbm-dev
            - libfftw3-dev
            - libcfitsio-dev
            - libboost-python-dev

    homebrew:
       update: false
       packages:
            - python3
            - pkg-config
            - git
            - fftw

install:
    - pip3 install \
      setuptools \
      numpy \
      scipy \
      aipy \
      astropy \
      codecov

    - pip3 install .

script:
    - cd tests

script:
    - cd tests
    - coverage run -m unittest discover

after_success:
    - cd tests
    - codecov
